#pragma once
#include "impl.hpp"
#include <SDL2/SDL.h>
void SGUIloadWidget();
void SGUIDrawWidget();



SDL_AddEventWatch
SDL_EventEnabled
SDL_FilterEvents
SDL_FlushEvent
SDL_FlushEvents
SDL_GetEventFilter
SDL_GetWindowFromEvent
SDL_HasEvent
SDL_HasEvents
SDL_PeepEvents
SDL_PollEvent
SDL_PumpEvents
SDL_PushEvent
SDL_RegisterEvents
SDL_RemoveEventWatch
SDL_SetEventEnabled
SDL_SetEventFilter
SDL_WaitEvent
SDL_WaitEventTimeout
//Datatypes
// Structs
SDL_AudioDeviceEvent
SDL_CameraDeviceEvent
SDL_ClipboardEvent
SDL_CommonEvent
SDL_DisplayEvent
SDL_DropEvent
SDL_Event
SDL_GamepadAxisEvent
SDL_GamepadButtonEvent
SDL_GamepadDeviceEvent
SDL_GamepadSensorEvent
SDL_GamepadTouchpadEvent
SDL_JoyAxisEvent
SDL_JoyBallEvent
SDL_JoyBatteryEvent
SDL_JoyButtonEvent
SDL_JoyDeviceEvent
SDL_JoyHatEvent
SDL_KeyboardDeviceEvent
SDL_KeyboardEvent
SDL_MouseButtonEvent
SDL_MouseDeviceEvent
SDL_MouseMotionEvent
SDL_MouseWheelEvent
SDL_PenAxisEvent
SDL_PenButtonEvent
SDL_PenMotionEvent
SDL_PenProximityEvent
SDL_PenTouchEvent
SDL_QuitEvent
SDL_SensorEvent
SDL_TextEditingCandidatesEvent
SDL_TextEditingEvent
SDL_TextInputEvent
SDL_TouchFingerEvent
SDL_UserEvent
SDL_WindowEvent

